version: '3.7'

networks:
  football-test-network-default:

services:
  nginx:
    build:
      context: nginx
    ports:
        - "8080:80"
    volumes:
      - ./src:/var/www
#      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    env_file:
      - .env
    networks:
      - football-test-network-default

  mysql:
    image: mysql:8
    container_name: football-test-db
    restart: unless-stopped
    environment:
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_USER: ${DB_USERNAME}
        SERVICE_TAGS: dev
        SERVICE_NAME: mysql
    volumes:
        - ./db/data:/var/lib/mysql
        - ./db/config.cnf:/etc/mysql/conf.d/config.cnf
    env_file:
      - .env
    networks:
      - football-test-network-default

  php:
    build:
      context: php
    volumes:
      - ./src:/var/www
#      - ./php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    env_file:
      - .env
    networks:
      - football-test-network-default

  npm:
    image: node:13.7
    volumes:
      - ./src:/var/www
    working_dir: /var/www
    entrypoint: ['npm']
    env_file:
      - .env
    networks:
      - football-test-network-default
